language: perl
env:
  global:
    - WIKI_TOOLKIT_MYSQL_DBNAME=wikitest
    - WIKI_TOOLKIT_MYSQL_DBUSER=root
    - WIKI_TOOLKIT_MYSQL_DBHOST=localhost
perl:
  - "5.22"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE wikitest;'
  - cpanm --quiet --notest DBD::SQLite Plucene File::Spec::Functions Lucy File::Path Lingua::Stem DBD::Pg DBD::mysql DBIx::FullTextSearch Test::Pod Test::MockObject Hook::LexWrap Wiki::Toolkit::Formatter::UseMod
sudo: false
script: perl Makefile.PL && make && prove -v
