language: perl
env:
  global:
    - WIKI_TOOLKIT_PG_DBNAME=wikitest
    - WIKI_TOOLKIT_PG_DBUSER=postgres
    - WIKI_TOOLKIT_PG_DBHOST=localhost
perl:
  - "5.22"
services:
  - postgresql
before_install:
  - psql -c 'create database wikitest;' -U postgres
  - cpanm --quiet --notest DBD::SQLite Plucene File::Spec::Functions Lucy File::Path Lingua::Stem DBD::Pg DBD::mysql DBIx::FullTextSearch Test::Pod Test::MockObject Hook::LexWrap Wiki::Toolkit::Formatter::UseMod
sudo: false
